---
title: "predict the goose"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(fpp2)
library(lubridate)
library(timeDate)
source("stathol.R")
knitr::opts_chunk$set(echo = FALSE)
```

```{r getdata, echo=FALSE, message = FALSE,warning = FALSE}
goose <- read_csv("data.csv")
goose$date <- parse_date(goose$date, "%m/%d/%Y")
goose$day=as.factor(weekdays(goose$date))
start.day <- c(year(goose$date[1]),as.numeric(format(goose$date[1], "%j")))
start.week <- c(isoweek(goose$date[1]),wday(goose$date[1],label=FALSE))
w.a.seas <- msts(goose$cyclists,seasonal.periods=c(7,365.25),start=start.day)
a.seas <- ts(goose$cyclists, frequency=365.25, start=start.day)
w.seas <- ts(goose$cyclists, frequency=7, start=start.week)
w.a.train <- subset(w.a.seas, end=length(w.a.seas)-14)
a.train<- subset(a.seas, end=length(a.seas)-14)
w.train<- subset(w.seas, end=length(w.seas)-14)
w.a.test <- subset(w.a.seas, start=length(w.a.seas)-13)
a.test <- subset(a.seas, start=length(a.seas)-13)
w.test <- subset(w.seas, start=length(w.seas)-13)
```

## Plot the whole series and just 2018


```{r goose, echo=FALSE, message = FALSE, warning = FALSE}
p1 <- autoplot(w.a.seas)+ylab("cyclists") + xlab("Years")+ggtitle("Goose: All Data")
p2 <- ggplot(filter(goose,year(date)=="2018"), aes(date, cyclists)) + xlab("Weeks")+ggtitle("Goose: 2018")+
  geom_line()+scale_x_date(date_breaks = "4 weeks", date_labels = "%W",date_minor_breaks = "1 week")

gridExtra::grid.arrange(p1,p2)
```

## SLT Decomposition

Of the whole series, assuming weekly and yearly seasonality.


```{r stl, echo=FALSE}
w.a.seas %>% mstl() %>% 
  autoplot() 
```

## forecast based on stlf

```{r goose-stlf, echo=FALSE}
stlfor <- w.a.train %>%  stlf(h=14) 
stlfor %>% autoplot(include=5*7) + xlab("Week")
accuracy(stlfor, w.a.test)
stlfor %>% checkresiduals()
```

## Forecast based on Dynamic harmonic regression

```{r chooseKs, echo=FALSE}
# rmse <- list()
# for (i in seq(3)){
#   for (j in seq(10)){
#   fit <- auto.arima(w.a.train, xreg = fourier(w.a.train, K = c(i,j)),
#     seasonal = FALSE, lambda = 0)
#   forfit <- forecast(fit,xreg=fourier(w.a.train, K=c(i,j), h=14))
#   rmse[[paste(i,j,sep=".")]] <-accuracy(forfit, w.a.test)["Test set","RMSE"]
#   } 
# }
# rmse[which(min(unlist(rmse))==rmse)]
```

```{r fourier, echo=FALSE}
ks <- c(2,2)
fourmod <- auto.arima(w.a.train, seasonal=FALSE,xreg=fourier(w.a.train, K=ks),lambda = 0)
fourfor <- fourmod %>% forecast(xreg=fourier(w.a.train, K=ks, h=14))
fourfor %>% autoplot(include=35) + ylab("cyclists") + xlab("Weeks")
accuracy(fourfor, w.a.test)
fourfor %>% checkresiduals()
```

## forecast based on TBATS

```{r goose-tbats, echo=FALSE}
tbatsfit <- w.a.train %>%  tbats() 
tbatsfor <- forecast(tbatsfit,h=14)
tbatsfor %>% autoplot(include=5*7) + xlab("Week")
accuracy(tbatsfor, w.a.test)
tbatsfor %>% checkresiduals()
```

## Arima with fourier for annual and holiday dummies
```{r holi, echo=FALSE,warning=FALSE,message=FALSE}
z <- fourier(a.train, K=2)
zf <- fourier(a.train, K=2, h=14)
holiday <- select(stat.hol(goose$date[1],tail(goose$date,n=1)-days(14)),-date)
holidayf <- select(stat.hol(tail(goose$date,n=1)-days(13),tail(goose$date,n=1)),-date)
xr <- cbind(z,holiday)
four.dum.mod <- auto.arima(w.train, xreg=xr, seasonal=TRUE)
four.dum.for <- forecast(four.dum.mod, xreg=cbind(zf,holidayf), h=14)
four.dum.for %>% autoplot(include=5*7) + xlab("Week")
accuracy(four.dum.for, w.test)
four.dum.for %>% checkresiduals()
```

## Combine the forecasts

```{r combine, echo=FALSE}
four.dum.for$mean <- ts(four.dum.for$mean, frequency=365.25, start = c(2018, 288))
stlfor$mean <- ts(stlfor$mean, frequency=365.25, start = c(2018, 288))
fourfor$mean <- ts(fourfor$mean, frequency=365.25, start = c(2018, 288))
tbatsfor$mean <- ts(tbatsfor$mean, frequency=365.25, start = c(2018, 288))
combf <- (fourfor$mean+stlfor$mean+tbatsfor$mean+four.dum.for$mean)/4
accuracy(combf,unclass(a.test))
```

```{r plots, echo=FALSE,warning=FALSE,message=FALSE}
end.of.series <- ts(subset(a.seas, start=length(a.seas)-(13+21)),start=c(2018, 288-21),frequency=365.25)
autoplot(end.of.series)+
  autolayer(four.dum.for$mean, series="Arima+Fourier+Dummies")+
  autolayer(stlfor$mean,series="STL Decomp")+
  autolayer(fourfor$mean,series="Arima+Fourier")+
  autolayer(tbatsfor$mean,series="TBATS")+
  autolayer(combf,series="Combined")+
  xlab("Time")+ylab("cyclists")+ggtitle("Goose")+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5),labels = NULL, minor_breaks = NULL) 

```
